### ISSUE TITLE
device_gateway and gatewaytemplate: add missing interface attributes

### ISSUE THREAD

**Issue by tmunzer** [Juniper/terraform-provider-mist#28]
from OpenAPI Spec:
```yaml 
        ae_disable_lacp:
          default: false
          description: if `aggregated`==`true`. To disable LCP support for the AE
            interface
          type: boolean
        ae_idx:
          description: if `aggregated`==`true`. Users could force to use the designated
            AE name
          nullable: true
          type: integer
        ae_lacp_force_up:
          default: false
          description: 'For SRX Only, if `aggregated`==`true`.Sets the state of the
            interface as UP when the peer has limited LACP capability.\n

            Use case: When a device connected to this AE port is ZTPing for the first
            time, it will not have LACP configured on the other end\n

            Note: Turning this on will enable force-up on one of the interfaces in
            the bundle only'
          type: boolean
        aggregated:
          default: false
          type: boolean
        critical:
          default: false
          description: if want to generate port up/down alarm, set it to true
          type: boolean
```
